# 아이리스 품종 분류
- github csv url: https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv


In [ ]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

In [ ]:
# 1.과거의 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [ ]:
# 원핫인코딩
인코딩 = pd.get_dummies(아이리스)
인코딩.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [ ]:
# 칼럼이름 출력
print(인코딩.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [ ]:
# 독립변수, 종속변수
독립 = 인코딩[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 인코딩[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [ ]:
# 2. 모델의 구조를 만듭니다
X = tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3, activation='softmax')(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy')

In [ ]:
# 3.데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=100)

Epoch 1/100
5/5 [==============================] - 4s 5ms/step - loss: 2.1606 - accuracy: 0.3333
Epoch 2/100
5/5 [==============================] - 0s 3ms/step - loss: 2.0625 - accuracy: 0.3400
Epoch 3/100
5/5 [==============================] - 0s 4ms/step - loss: 1.9958 - accuracy: 0.3733
Epoch 4/100
5/5 [==============================] - 0s 3ms/step - loss: 1.9389 - accuracy: 0.3933
Epoch 5/100
5/5 [==============================] - 0s 3ms/step - loss: 1.8872 - accuracy: 0.4267
Epoch 6/100
5/5 [==============================] - 0s 3ms/step - loss: 1.8386 - accuracy: 0.4267
Epoch 7/100
5/5 [==============================] - 0s 3ms/step - loss: 1.7910 - accuracy: 0.4600
Epoch 8/100
5/5 [==============================] - 0s 3ms/step - loss: 1.7441 - accuracy: 0.5000
Epoch 9/100
5/5 [==============================] - 0s 3ms/step - loss: 1.6980 - accuracy: 0.5067
Epoch 10/100
5/5 [==============================] - 0s 3ms/step - loss: 1.6533 - accuracy: 0.5333
Epoch 11/100
5/5 [===========

In [ ]:
# 모델을 이용합니다.
# 맨 처음 데이터 5개
print(model.predict(독립[:5]))
print(종속[:5])

# 맨 마지막 데이터 5개
print(model.predict(독립[-5:]))
print(종속[-5:])


1/1 [==============================] - 0s 128ms/step
[[0.6986291  0.22383219 0.07753868]
 [0.6252734  0.30201298 0.07271361]
 [0.6692626  0.24431619 0.0864212 ]
 [0.6316832  0.25307122 0.11524562]
 [0.7111283  0.19967602 0.08919574]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
1/1 [==============================] - 0s 42ms/step
[[0.09433184 0.48609808 0.41957015]
 [0.0917261  0.51972884 0.38854504]
 [0.09572766 0.3918164  0.51245594]
 [0.0686136  0.20788884 0.72349757]
 [0.08269091 0.24192362 0.6753855 ]]
     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1


In [ ]:
# weights & bias 출력
print(model.get_weights())

[array([[ 0.57489026,  0.930841  , -0.36553624],
       [ 0.24837595, -0.7150128 ,  0.5311812 ],
       [-0.5455317 , -0.3842708 ,  0.85376143],
       [ 0.3413748 ,  0.8717596 ,  0.35067305]], dtype=float32), array([ 0.06809215,  0.15453829, -0.28476423], dtype=float32)]
