<a href="https://colab.research.google.com/github/JTechhub/JTechhub.github.io/blob/main/practice5_multilayer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 히든레이어

- 보스턴 집값 예측: https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv

- 아이리스 품종 분류: https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv


In [ ]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

## 보스턴 집값 예측

In [ ]:
# 1.과거의 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스턴 = pd.read_csv(파일경로)

# 종속변수, 독립변수
독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox',
            'rm', 'age', 'dis', 'rad', 'tax',
            'ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']]
print(독립.shape, 종속.shape)

(506, 13) (506, 1)


In [ ]:
# 2. 모델의 구조를 만듭니다
X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(10, activation='swish')(X)
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [ ]:
# 모델 구조 확인
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 13)]              0         
                                                                 
 dense (Dense)               (None, 10)                140       
                                                                 
 dense_1 (Dense)             (None, 1)                 11        
                                                                 
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# 3.데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=1000, verbose = 0)
model.fit(독립, 종속, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 6ms/step - loss: 0.0440 - accuracy: 0.9800
Epoch 2/10
5/5 [==============================] - 0s 6ms/step - loss: 0.0505 - accuracy: 0.9867
Epoch 3/10
5/5 [==============================] - 0s 5ms/step - loss: 0.0434 - accuracy: 0.9867
Epoch 4/10
5/5 [==============================] - 0s 6ms/step - loss: 0.0421 - accuracy: 0.9800
Epoch 5/10
5/5 [==============================] - 0s 6ms/step - loss: 0.0442 - accuracy: 0.9800
Epoch 6/10
5/5 [==============================] - 0s 5ms/step - loss: 0.0478 - accuracy: 0.9867
Epoch 7/10
5/5 [==============================] - 0s 5ms/step - loss: 0.0425 - accuracy: 0.9800
Epoch 8/10
5/5 [==============================] - 0s 5ms/step - loss: 0.0421 - accuracy: 0.9867
Epoch 9/10
5/5 [==============================] - 0s 6ms/step - loss: 0.0513 - accuracy: 0.9800
Epoch 10/10
5/5 [==============================] - 0s 5ms/step - loss: 0.0469 - accuracy: 0.9800


In [ ]:
# 4. 모델을 이용합니다
print(model.predict(독립[:5]))
print(종속[:5])

1/1 [==============================] - 0s 25ms/step
[[9.9999070e-01 6.4857095e-06 2.8607301e-06]
 [9.9998140e-01 1.3630549e-05 4.9712976e-06]
 [9.9997592e-01 1.7398150e-05 6.6901239e-06]
 [9.9996841e-01 2.3489330e-05 8.1428161e-06]
 [9.9998915e-01 7.4787763e-06 3.3767785e-06]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


## 아이리스 품종 분류


In [ ]:
# 1.과거의 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)

# 원핫인코딩
아이리스 = pd.get_dummies(아이리스)

# 종속변수, 독립변수
독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 아이리스[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [ ]:
# 2. 모델의 구조를 만듭니다
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation="swish")(X)
H = tf.keras.layers.Dense(8, activation="swish")(H)
H = tf.keras.layers.Dense(8, activation="swish")(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy')

In [ ]:
# 모델 구조 확인
model.summary()

Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 4)]               0         
                                                                 
 dense_2 (Dense)             (None, 8)                 40        
                                                                 
 dense_3 (Dense)             (None, 8)                 72        
                                                                 
 dense_4 (Dense)             (None, 8)                 72        
                                                                 
 dense_5 (Dense)             (None, 3)                 27        
                                                                 
Total params: 211
Trainable params: 211
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# 3.데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=100)

Epoch 1/100
5/5 [==============================] - 2s 6ms/step - loss: 1.2734 - accuracy: 0.3333
Epoch 2/100
5/5 [==============================] - 0s 6ms/step - loss: 1.1805 - accuracy: 0.3333
Epoch 3/100
5/5 [==============================] - 0s 6ms/step - loss: 1.1391 - accuracy: 0.3333
Epoch 4/100
5/5 [==============================] - 0s 5ms/step - loss: 1.1124 - accuracy: 0.3333
Epoch 5/100
5/5 [==============================] - 0s 7ms/step - loss: 1.0909 - accuracy: 0.3467
Epoch 6/100
5/5 [==============================] - 0s 6ms/step - loss: 1.0734 - accuracy: 0.4267
Epoch 7/100
5/5 [==============================] - 0s 5ms/step - loss: 1.0576 - accuracy: 0.5067
Epoch 8/100
5/5 [==============================] - 0s 5ms/step - loss: 1.0407 - accuracy: 0.6667
Epoch 9/100
5/5 [==============================] - 0s 6ms/step - loss: 1.0255 - accuracy: 0.6667
Epoch 10/100
5/5 [==============================] - 0s 5ms/step - loss: 1.0096 - accuracy: 0.6600
Epoch 11/100
5/5 [===========

In [ ]:
# 4. 모델을 이용합니다
print(model.predict(독립[0:5]))
print(종속[0:5])

1/1 [==============================] - 0s 82ms/step
[[9.9838626e-01 1.5427714e-03 7.0958667e-05]
 [9.9600071e-01 3.8239164e-03 1.7540489e-04]
 [9.9718505e-01 2.6722893e-03 1.4267853e-04]
 [9.9585968e-01 3.9372193e-03 2.0310613e-04]
 [9.9851161e-01 1.4198169e-03 6.8526104e-05]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
